import SinglePost from "@/components/Post/SinglePost";
import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

type AllPosts = {
  allPosts: {
    id: string;
    title: string;
    description: string;
    date: string;
    slug: string;
    tags: string[];
  }[];
};

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  return {
    props: {
      allPosts: allPosts,
    },
    revalidate: 60 * 60,
  };
};

export default function Home({ allPosts }: AllPosts) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-10">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog🚀</h1>
        {allPosts.map(
          (post: {
            id: string;
            title: string;
            description: string;
            date: string;
            slug: string;
            tags: string[];
          }) => (
            <div className="mx-4" key={post.id}>
              <SinglePost
                id={post.id}
                title={post.title}
                description={post.description}
                date={post.date}
                slug={post.slug}
                tags={post.tags}
              />
            </div>
          )
        )}
      </main>
    </div>
  );
}
